[package]
name = "ingestor"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
serde_millis = "0.1"
serde_json = "1"
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors" }
serde = { version = "1", features = ['derive'] }
common-interfaces = { path = "../common-interfaces" }
