[package]
name = "ingestor"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/dioxuslabs/dioxus", features = [
    "desktop",
], branch = "jk/coroutine-coroutineoverhaul" }
uart-types = { path = "../uart-types" }
futures = "0.3.21"
futures-util = "0.3.21"
log = "0.4.14"
postcard = "0.7.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio-serial = "5.4.1"
tokio = { version = "1.17.0", features = ["full"] }
zerocopy = "0.6.1"
futures-channel = "0.3.21"
