[package]
name = "ingestor"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_millis = "0.1"
serde_json = "1"
serde = { version = "1", features = ['derive'] }
common-interfaces = { path = "../common-interfaces" }
tide = "0.15.0"
tide-websockets = "0.1.0"
async-std = { version = "1.8.0", features = ["attributes"] }
log = "0.4"
fern = { version = "0.6.0", features = ["colored"] }
async-channel = "1.5.1"
futures-lite = "1.11.2"
anyhow = "1.0.35"


# rocket = { git = "https://github.com/SergioBenitez/Rocket" }
# rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket" }
# rocket_cors = { git = "https://github.com/lawliet89/rocket_cors" }
