# [target.arm-unknown-linux-musleabihf]
# linker = "arm-linux-musleabihf-gcc"
[build]
target = "arm-unknown-linux-musleabi"
# target = "armv7-unknown-linux-musleabihf"

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-musleabihf-ld"
# linker = "arm-linux-gnueabihf-ld"
# [target.arm-unknown-linux-musleabi]
# linker = "arm-linux-gnueabihf-ld"

# [target.armv7-unknown-linux-musleabi]
# [target.armv7-unknown-linux-musleabihf]
# linker = "arm-linux--ld"
