[package]
name = "tag"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.3"
cortex-m-semihosting = "0.3.7"
embedded-hal = "0.2.6"
embedded-timeout-macros = "0.3.0"
lis2dh12 = "0.6.7"
heapless = "0.7.8"
nb = "1.0.0"
dwm1001 = { version = "0.6.0", features = [
    "rt",
    "dev",
], path = "../../../../Tinkering/rust-dw1000/dwm1001" }
cortex-m-rt = "*"
defmt = "0.3.0"
defmt-rtt = "0.3.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
postcard = { version = "0.7.3", default-features = false }
serde = { version = "1.0.136", features = ["derive"], default-features = false }
accelerometer = "0.12.0"
mpu6050 = "0.1.5"
shared-bus = "0.2.2"
zerocopy = "0.6.1"
uart-types = { path = "../uart-types" }
ssmarshal = { version = "1.0.0", default-features = false }


[dependencies.nrf52832-hal]
version = "0.14.0"
default-features = false
features = ["xxAA-package"]

# # cargo build/run
# [profile.dev]
# codegen-units = 1
# debug = 2
# debug-assertions = true # <-
# incremental = false
# opt-level = 3           # <-
# overflow-checks = true  # <-

# # cargo test
# [profile.test]
# codegen-units = 1
# debug = 2
# debug-assertions = true # <-
# incremental = false
# opt-level = 3           # <-
# overflow-checks = true  # <-

# # cargo build/run --release
# [profile.release]
# codegen-units = 1
# debug = 2
# debug-assertions = false # <-
# incremental = false
# lto = 'fat'
# opt-level = 3            # <-
# overflow-checks = false  # <-

# # cargo test --release
# [profile.bench]
# codegen-units = 1
# debug = 2
# debug-assertions = false # <-
# incremental = false
# lto = 'fat'
# opt-level = 3            # <-
# overflow-checks = false  # <-
