[package]
name = "common-interfaces"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_millis = "0.1"
serde_json = "1"
serde = { version = "1", features = ['derive'] }
instant = { version = "0.1.6", feautres = ["wasm-bindgen"] }
