[package]
name = "web_viewer"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../../../Projects/yew/yew" }
yew-functional = { path = "../../../../Projects/yew/yew-functional" }
wasm-logger = "0.2.0"
log = "0.4.11"
wasm-bindgen = "0.2.69"
yew-recoil = { path = "../../../../YewProjects/packages/yew-recoil" }
common-interfaces = { path = "../common-interfaces" }
reqwest = { version = "0.10", features = ["blocking", "json"] }
wasm-bindgen-futures = "0.4.19"
