[package]
name = "gateway"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.13.1"
reqwest = { version = "0.11.9", features = [
    "rustls-tls",
    "json",
], default-features = false }
anyhow = "1.0.35"
log = "0.4"
fern = { version = "0.6.0", features = ["colored"] }
futures-channel = "0.3.21"
futures-lite = "1.11.2"
