[package]
name = "gateway"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
reqwest = { version = "0.10.10", features = ["rustls-tls", "json"], default-features = false }
anyhow = "1.0.35"
async-std = { version = "1.8.0", features = ["tokio02", "attributes"] }
log = "0.4"
fern = { version = "0.6.0", features = ["colored"] }
async-channel = "1.5.1"
futures-lite = "1.11.2"
