use dioxus::core::to_owned;
use dioxus::prelude::*;
use futures_channel::mpsc::UnboundedReceiver;
use futures_util::stream::StreamExt;
use serde::{Deserialize, Serialize};
use std::{borrow::Borrow, sync::RwLock, time::Duration};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};
use tokio_serial::SerialPortBuilderExt;
use uuid::Uuid;
use zerocopy::AsBytes;
