[package]
name = "mobile-firmware"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = { version = "0.2.4", features = ["unproven"] }
embedded-timeout-macros = "0.3.0"
cortex-m = { version = "0.6.3", features = ["const-fn"] }
cortex-m-rt = "0.6.13"
defmt = { git = "https://github.com/knurling-rs/defmt", rev = "dd056e6b7ea807e43f851c75b6fa24bfd7cf9f5a" }
defmt-rtt = { git = "https://github.com/knurling-rs/defmt", rev = "dd056e6b7ea807e43f851c75b6fa24bfd7cf9f5a" }
panic-probe = { git = "https://github.com/knurling-rs/defmt", rev = "dd056e6b7ea807e43f851c75b6fa24bfd7cf9f5a" }
# panic-probe = { version = "0.1.0", features = ["print-defmt"] }

dw1000 = { git = "https://github.com/braun-embedded/rust-dw1000" }
nrf52832-hal = { version = "0.12.0", default-features = false, features = ["xxAA-package"] }
lis2dh12 = "0.6.0"
nb = "1.0.0"
heapless = "0.5.6"


[[example]]
name = "anchor"
path = "examples/anchor.rs"

[[example]]
name = "tag"
path = "examples/tag.rs"


[features]
# set logging levels here
default = ["defmt-default"]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[profile.dev]
debug = 1 # default is `true`; not needed if not already overridden
incremental = false 
codegen-units = 1 
lto = true 
opt-level = 1 

[profile.release]
debug = 1 # default is `false`; using `true` is also OK
incremental = false 
codegen-units = 1 
lto = true 
opt-level = 3
